name: pyobjmap
channels:
- conda-forge
- defaults
dependencies:
- python=3.10.*
- matplotlib
- numpy
- pip
- scipy
- ipykernel
- munch
- cartopy
- xarray
- netcdf4
- sympy
- black
- isort
- jupytext
- pydap
- lxml
- pip:
    - -e .